steps:
  - task: Cache@2
    inputs:
      key: 'pip | "$(Agent.OS)" | pyproject.toml'
      restoreKeys: |
        pip | "$(Agent.OS)"
      path: $(Pipeline.Workspace)/.pip-cache
    displayName: 'Cache de dependencias de pip'

  - script: |
      python -m pip install --upgrade pip
      pip install . --cache-dir $(Pipeline.Workspace)/.pip-cache
    displayName: 'Instala dependencias'